// IGCSE Minimum core vocabulary list 1 & 2
// Browser-compatible version
// Assigning to window to ensure global access without module system
window.WORDS = [
 // ==========================================
  // List 1: High Frequency Language
  // ==========================================
  
  // Topic: Pronouns
  { id: 1, chinese: "我", english: "I, me", jyutping: "ngo5", topic: "Pronouns" },
  { id: 2, chinese: "你", english: "you", jyutping: "nei5", topic: "Pronouns" },
  { id: 3, chinese: "他", english: "he, him", jyutping: "taa1", topic: "Pronouns" },
  { id: 4, chinese: "她", english: "she, her", jyutping: "taa1", topic: "Pronouns" },
  { id: 5, chinese: "我們", english: "we, us", jyutping: "ngo5 mun4", topic: "Pronouns" },
  { id: 6, chinese: "你們", english: "you (plural)", jyutping: "nei5 mun4", topic: "Pronouns" },
  { id: 7, chinese: "他們", english: "they, them", jyutping: "taa1 mun4", topic: "Pronouns", synonym_group: 1 },
  { id: 8, chinese: "她們", english: "they, them", jyutping: "taa1 mun4", topic: "Pronouns", synonym_group: 1 },
  { id: 9, chinese: "這", english: "this", jyutping: "ze3", topic: "Pronouns" },
  { id: 10, chinese: "那", english: "that", jyutping: "naa5", topic: "Pronouns" },

  // Topic: Countries/Languages
  { id: 11, chinese: "中國", english: "China", jyutping: "zung1 gwok3", topic: "Countries/Languages" },
  { id: 12, chinese: "英國", english: "United Kingdom", jyutping: "jing1 gwok3", topic: "Countries/Languages" },
  { id: 13, chinese: "法國", english: "France", jyutping: "faat3 gwok3", topic: "Countries/Languages" },
  { id: 14, chinese: "美國", english: "United States", jyutping: "mei5 gwok3", topic: "Countries/Languages" },
  { id: 15, chinese: "國家", english: "country", jyutping: "gwok3 gaa1", topic: "Countries/Languages" },
  { id: 16, chinese: "國籍", english: "nationality", jyutping: "gwok3 zik6", topic: "Countries/Languages" },
  { id: 17, chinese: "漢語", english: "Modern Standard Chinese/Mandarin", jyutping: "hon3 jyu5", topic: "Countries/Languages", synonym_group: 2 },
  { id: 18, chinese: "普通話", english: "Modern Standard Chinese/Mandarin", jyutping: "pou2 tung1 waa2", topic: "Countries/Languages", synonym_group: 2 },
  { id: 19, chinese: "法文", english: "French language", jyutping: "faat3 man4", topic: "Countries/Languages" },
  { id: 20, chinese: "英語", english: "English language", jyutping: "jing1 jyu5", topic: "Countries/Languages" },
  { id: 21, chinese: "外語", english: "Foreign language", jyutping: "ngoi6 jyu5", topic: "Countries/Languages" },
  { id: 22, chinese: "語言", english: "language", jyutping: "jyu5 jin4", topic: "Countries/Languages" },

  // Topic: Numbers
  { id: 23, chinese: "一", english: "one", jyutping: "jat1", topic: "Numbers" },
  { id: 24, chinese: "二", english: "two", jyutping: "ji6", topic: "Numbers", synonym_group: 3 },
  { id: 25, chinese: "三", english: "three", jyutping: "saam1", topic: "Numbers" },
  { id: 26, chinese: "四", english: "four", jyutping: "sei3", topic: "Numbers" },
  { id: 27, chinese: "五", english: "five", jyutping: "ng5", topic: "Numbers" },
  { id: 28, chinese: "六", english: "six", jyutping: "luk6", topic: "Numbers" },
  { id: 29, chinese: "七", english: "seven", jyutping: "cat1", topic: "Numbers" },
  { id: 30, chinese: "八", english: "eight", jyutping: "baat3", topic: "Numbers" },
  { id: 31, chinese: "九", english: "nine", jyutping: "gau2", topic: "Numbers" },
  { id: 32, chinese: "十", english: "ten", jyutping: "sap6", topic: "Numbers" },
  { id: 33, chinese: "兩", english: "two (quantity)", jyutping: "loeng5", topic: "Numbers", synonym_group: 3 },
  { id: 34, chinese: "百", english: "hundred", jyutping: "baak3", topic: "Numbers" },
  { id: 35, chinese: "千", english: "thousand", jyutping: "cin1", topic: "Numbers" },
  { id: 36, chinese: "多", english: "many, how (+ adjectives)", jyutping: "do1", topic: "Numbers" },
  { id: 37, chinese: "少", english: "few", jyutping: "siu2", topic: "Numbers" },
  { id: 38, chinese: "幾個", english: "several", jyutping: "gei2 go3", topic: "Numbers" },

  // Topic: Quantities
  { id: 39, chinese: "個", english: "measure word (common)", jyutping: "go3", topic: "Quantities" },
  { id: 40, chinese: "本", english: "measure word (books)", jyutping: "bun2", topic: "Quantities" },
  { id: 41, chinese: "隻", english: "measure word (animals)", jyutping: "zi2", topic: "Quantities" },
  { id: 42, chinese: "件", english: "measure word (clothing)", jyutping: "gin6", topic: "Quantities" },
  { id: 43, chinese: "張", english: "measure word (flat objects)", jyutping: "zoeng1", topic: "Quantities" },
  { id: 44, chinese: "條", english: "measure word (long/narrow)", jyutping: "tiu4", topic: "Quantities" },
  { id: 45, chinese: "片", english: "measure word (slice)", jyutping: "pin3", topic: "Quantities" },

  // Topic: Colours
  { id: 46, chinese: "顏色", english: "colour", jyutping: "ngaan4 sik1", topic: "Colours" },
  { id: 47, chinese: "白", english: "white", jyutping: "baak6", topic: "Colours" },
  { id: 48, chinese: "黑", english: "black", jyutping: "hak1", topic: "Colours" },
  { id: 49, chinese: "紅", english: "red", jyutping: "hung4", topic: "Colours" },
  { id: 50, chinese: "黃", english: "yellow", jyutping: "wong4", topic: "Colours" },
  { id: 51, chinese: "藍", english: "blue", jyutping: "laam4", topic: "Colours" },
  { id: 52, chinese: "綠", english: "green", jyutping: "luk6", topic: "Colours" },
  { id: 53, chinese: "金", english: "gold", jyutping: "gam1", topic: "Colours" },
  { id: 54, chinese: "銀", english: "silver", jyutping: "ngan4", topic: "Colours" },

  // Topic: Time
  { id: 55, chinese: "現在", english: "now", jyutping: "jin6 zoi6", topic: "Time" },
  { id: 56, chinese: "點", english: "o'clock", jyutping: "dim2", topic: "Time" },
  { id: 57, chinese: "半", english: "half", jyutping: "bun3", topic: "Time" },
  { id: 58, chinese: "時間", english: "time", jyutping: "si4 gaan1", topic: "Time" },
  { id: 59, chinese: "月", english: "month", jyutping: "jyut6", topic: "Time" },
  { id: 60, chinese: "號", english: "date (number)", jyutping: "hou6", topic: "Time", synonym_group: 15 },
  { id: 61, chinese: "日", english: "date (day)", jyutping: "jat6", topic: "Time", synonym_group: 15 },
  { id: 62, chinese: "昨天", english: "yesterday", jyutping: "zok3 tin1", topic: "Time" },
  { id: 63, chinese: "今天", english: "today", jyutping: "gam1 tin1", topic: "Time" },
  { id: 64, chinese: "明天", english: "tomorrow", jyutping: "ming4 tin1", topic: "Time" },
  { id: 65, chinese: "每天", english: "every day", jyutping: "mui5 tin1", topic: "Time", synonym_group: 4 },
  { id: 66, chinese: "天天", english: "every day", jyutping: "tin1 tin1", topic: "Time", synonym_group: 4 },
  { id: 67, chinese: "去年", english: "last year", jyutping: "heoi3 nin4", topic: "Time" },
  { id: 68, chinese: "今年", english: "this year", jyutping: "gam1 nin4", topic: "Time" },
  { id: 69, chinese: "明年", english: "next year", jyutping: "ming4 nin4", topic: "Time" },
  { id: 70, chinese: "早上", english: "morning", jyutping: "zou2 soeng6", topic: "Time", synonym_group: 16 },
  { id: 71, chinese: "上午", english: "morning, forenoon", jyutping: "soeng6 ng5", topic: "Time", synonym_group: 16 },
  { id: 72, chinese: "中午", english: "midday", jyutping: "zung1 ng5", topic: "Time" },
  { id: 73, chinese: "下午", english: "afternoon", jyutping: "haa6 ng5", topic: "Time" },
  { id: 74, chinese: "晚上", english: "evening", jyutping: "maan5 soeng6", topic: "Time" },
  { id: 75, chinese: "星期", english: "week", jyutping: "sing1 kei4", topic: "Time" },
  { id: 76, chinese: "週末", english: "weekend", jyutping: "zau1 mut6", topic: "Time" },
  { id: 77, chinese: "上(個)星期", english: "last week", jyutping: "soeng6 (go3) sing1 kei4", topic: "Time" },
  { id: 78, chinese: "這個星期", english: "this week", jyutping: "ze3 go3 sing1 kei4", topic: "Time" },
  { id: 79, chinese: "下(個)星期", english: "next week", jyutping: "haa6 (go3) sing1 kei4", topic: "Time" },
  { id: 80, chinese: "上個月", english: "last month", jyutping: "soeng6 go3 jyut6", topic: "Time" },
  { id: 81, chinese: "這個月", english: "this month", jyutping: "ze3 go3 jyut6", topic: "Time" },
  { id: 82, chinese: "下個月", english: "next month", jyutping: "haa6 go3 jyut6", topic: "Time" },
  { id: 83, chinese: "小時", english: "hour", jyutping: "siu2 si4", topic: "Time", synonym_group: 5 },
  { id: 84, chinese: "鐘頭", english: "hour", jyutping: "zung1 tau4", topic: "Time", synonym_group: 5 },
  { id: 85, chinese: "分", english: "minute", jyutping: "fan1", topic: "Time", synonym_group: 6 },
  { id: 86, chinese: "分鐘", english: "minute", jyutping: "fan1 zung1", topic: "Time", synonym_group: 6 },
  { id: 87, chinese: "從……到", english: "from...to...", jyutping: "cung4...dou3", topic: "Time" },
  { id: 88, chinese: "將來", english: "future, in the future", jyutping: "zoeng1 loi4", topic: "Time" },
  { id: 89, chinese: "……以前", english: "before...", jyutping: "...ji5 cin4", topic: "Time" },
  { id: 90, chinese: "……以後", english: "after...", jyutping: "...ji5 hau6", topic: "Time" },
  { id: 91, chinese: "……的時候", english: "when, at the time of...", jyutping: "...dik1 si4 hau6", topic: "Time" },
  { id: 92, chinese: "總是", english: "always", jyutping: "zung2 si6", topic: "Time" },
  { id: 93, chinese: "有時候", english: "sometimes", jyutping: "jau5 si4 hau6", topic: "Time" },
  { id: 94, chinese: "常常", english: "often", jyutping: "soeng4 soeng4", topic: "Time" },
  { id: 95, chinese: "已經", english: "already", jyutping: "ji5 ging1", topic: "Time" },
  { id: 96, chinese: "馬上", english: "immediately", jyutping: "maa5 soeng6", topic: "Time" },
  { id: 97, chinese: "很久", english: "(for a) long time", jyutping: "han2 gau2", topic: "Time" },
  { id: 98, chinese: "剛才", english: "just now", jyutping: "gong1 coi4", topic: "Time", synonym_group: 38 },
  { id: 99, chinese: "剛", english: "just", jyutping: "gong1", topic: "Time", synonym_group: 38 },

  // Topic: Days
  { id: 100, chinese: "星期一", english: "Monday", jyutping: "sing1 kei4 jat1", topic: "Days" },
  { id: 101, chinese: "星期二", english: "Tuesday", jyutping: "sing1 kei4 ji6", topic: "Days" },
  { id: 102, chinese: "星期三", english: "Wednesday", jyutping: "sing1 kei4 saam1", topic: "Days" },
  { id: 103, chinese: "星期四", english: "Thursday", jyutping: "sing1 kei4 sei3", topic: "Days" },
  { id: 104, chinese: "星期五", english: "Friday", jyutping: "sing1 kei4 ng5", topic: "Days" },
  { id: 105, chinese: "星期六", english: "Saturday", jyutping: "sing1 kei4 luk6", topic: "Days" },
  { id: 106, chinese: "星期日", english: "Sunday", jyutping: "sing1 kei4 jat6", topic: "Days", synonym_group: 7 },
  { id: 107, chinese: "星期天", english: "Sunday", jyutping: "sing1 kei4 tin1", topic: "Days", synonym_group: 7 },

  // Topic: Months
  { id: 108, chinese: "一月", english: "January", jyutping: "jat1 jyut6", topic: "Months" },
  { id: 109, chinese: "二月", english: "February", jyutping: "ji6 jyut6", topic: "Months" },
  { id: 110, chinese: "三月", english: "March", jyutping: "saam1 jyut6", topic: "Months" },
  { id: 111, chinese: "四月", english: "April", jyutping: "sei3 jyut6", topic: "Months" },
  { id: 112, chinese: "五月", english: "May", jyutping: "ng5 jyut6", topic: "Months" },
  { id: 113, chinese: "六月", english: "June", jyutping: "luk6 jyut6", topic: "Months" },
  { id: 114, chinese: "七月", english: "July", jyutping: "cat1 jyut6", topic: "Months" },
  { id: 115, chinese: "八月", english: "August", jyutping: "baat3 jyut6", topic: "Months" },
  { id: 116, chinese: "九月", english: "September", jyutping: "gau2 jyut6", topic: "Months" },
  { id: 117, chinese: "十月", english: "October", jyutping: "sap6 jyut6", topic: "Months" },
  { id: 118, chinese: "十一月", english: "November", jyutping: "sap6 jat1 jyut6", topic: "Months" },
  { id: 119, chinese: "十二月", english: "December", jyutping: "sap6 ji6 jyut6", topic: "Months" },

  // Topic: Verbs
  { id: 120, chinese: "是", english: "to be", jyutping: "si6", topic: "Verbs" },
  { id: 121, chinese: "有", english: "to have", jyutping: "jau5", topic: "Verbs" },
  { id: 122, chinese: "在", english: "to be in, at, on", jyutping: "zoi6", topic: "Verbs" },
  { id: 123, chinese: "叫", english: "to call, to be named", jyutping: "giu3", topic: "Verbs" },
  { id: 124, chinese: "說", english: "to say, speak, talk", jyutping: "syut3", topic: "Verbs" },
  { id: 125, chinese: "借", english: "borrow", jyutping: "ze3", topic: "Verbs" },
  { id: 126, chinese: "吃", english: "to eat", jyutping: "hek3", topic: "Verbs" },
  { id: 127, chinese: "喝", english: "to drink", jyutping: "hot3", topic: "Verbs" },
  { id: 128, chinese: "學(習)", english: "to learn, to study", jyutping: "hok6 (zaap6)", topic: "Verbs" },
  { id: 129, chinese: "打", english: "to play (ball), make (call)", jyutping: "daa2", topic: "Verbs" },
  { id: 130, chinese: "上", english: "to begin (lesson), ascend", jyutping: "soeng5", topic: "Verbs" },
  { id: 131, chinese: "下", english: "to descend, finish (lesson)", jyutping: "haa6", topic: "Verbs" },
  { id: 132, chinese: "做", english: "to do, to be (occupation)", jyutping: "zou6", topic: "Verbs" },
  { id: 133, chinese: "問", english: "to ask", jyutping: "man6", topic: "Verbs" },
  { id: 134, chinese: "懂", english: "to understand", jyutping: "dung2", topic: "Verbs" },
  { id: 135, chinese: "聽", english: "to listen/hear", jyutping: "ting1", topic: "Verbs" },
  { id: 136, chinese: "寫", english: "to write", jyutping: "se2", topic: "Verbs" },
  { id: 137, chinese: "畫(圖)", english: "to draw/paint", jyutping: "waa6 (tou4)", topic: "Verbs" },
  { id: 138, chinese: "練習", english: "practice", jyutping: "lin6 zaap6", topic: "Verbs" },
  { id: 139, chinese: "看", english: "to see, read, watch", jyutping: "hon3", topic: "Verbs" },
  { id: 140, chinese: "見", english: "to see, to meet", jyutping: "gin3", topic: "Verbs", synonym_group: 17 },
  { id: 141, chinese: "見面", english: "to see, to meet", jyutping: "gin3 min6", topic: "Verbs", synonym_group: 17 },
  { id: 142, chinese: "住", english: "to live", jyutping: "zyu6", topic: "Verbs" },
  { id: 143, chinese: "請", english: "to invite, please", jyutping: "cing2", topic: "Verbs" },
  { id: 144, chinese: "讓", english: "to let, allow", jyutping: "joeng6", topic: "Verbs" },
  { id: 145, chinese: "進", english: "to enter", jyutping: "zeon3", topic: "Verbs" },
  { id: 146, chinese: "出", english: "to go out", jyutping: "ceot1", topic: "Verbs" },
  { id: 147, chinese: "坐", english: "to sit, to travel by", jyutping: "zo6/co5", topic: "Verbs" },
  { id: 148, chinese: "唱", english: "to sing", jyutping: "coeng3", topic: "Verbs" },
  { id: 149, chinese: "踢", english: "to play (football), kick", jyutping: "tek3", topic: "Verbs" },
  { id: 150, chinese: "跳", english: "to jump", jyutping: "tiu3", topic: "Verbs" },
  { id: 151, chinese: "玩", english: "to play", jyutping: "wun6", topic: "Verbs" },
  { id: 152, chinese: "買", english: "to buy", jyutping: "maai5", topic: "Verbs" },
  { id: 153, chinese: "賣", english: "to sell", jyutping: "maai6", topic: "Verbs" },
  { id: 154, chinese: "穿", english: "to wear", jyutping: "cyun1", topic: "Verbs" },
  { id: 155, chinese: "用", english: "to use", jyutping: "jung6", topic: "Verbs" },
  { id: 156, chinese: "來", english: "to come", jyutping: "loi4", topic: "Verbs" },
  { id: 157, chinese: "去", english: "to go", jyutping: "heoi3", topic: "Verbs" },
  { id: 158, chinese: "回", english: "to return", jyutping: "wui4", topic: "Verbs" },
  { id: 159, chinese: "到", english: "to arrive", jyutping: "dou3", topic: "Verbs" },
  { id: 160, chinese: "試", english: "to try", jyutping: "si3", topic: "Verbs" },
  { id: 161, chinese: "停", english: "to stop", jyutping: "ting4", topic: "Verbs" },
  { id: 162, chinese: "等", english: "to wait for", jyutping: "dang2", topic: "Verbs" },
  { id: 163, chinese: "放", english: "to put, to set free", jyutping: "fong3", topic: "Verbs" },
  { id: 164, chinese: "給", english: "to give", jyutping: "kap1", topic: "Verbs" },
  { id: 165, chinese: "記", english: "to remember, write down", jyutping: "gei3", topic: "Verbs" },
  { id: 166, chinese: "忘", english: "to forget", jyutping: "mong4", topic: "Verbs" },
  { id: 167, chinese: "笑", english: "to laugh, smile", jyutping: "siu3", topic: "Verbs" },
  { id: 168, chinese: "洗", english: "to wash", jyutping: "sai2", topic: "Verbs" },
  { id: 169, chinese: "找", english: "to find, look for", jyutping: "zaau2", topic: "Verbs" },
  { id: 170, chinese: "過", english: "to cross, to celebrate", jyutping: "gwo3", topic: "Verbs" },
  { id: 171, chinese: "騎", english: "to ride (horse/bike)", jyutping: "ke4", topic: "Verbs" },
  { id: 172, chinese: "租", english: "to rent", jyutping: "zou1", topic: "Verbs" },
  { id: 173, chinese: "開車", english: "to drive a car", jyutping: "hoi1 ce1", topic: "Verbs" },
  { id: 174, chinese: "開", english: "to open, switch on", jyutping: "hoi1", topic: "Verbs" },
  { id: 175, chinese: "關", english: "to close, switch off", jyutping: "gwaan1", topic: "Verbs" },
  { id: 176, chinese: "換", english: "to change (money/clothes)", jyutping: "wun6", topic: "Verbs" },
  { id: 177, chinese: "花", english: "to spend (time/money)", jyutping: "faa1", topic: "Verbs", synonym_group: 40 },
  { id: 178, chinese: "送", english: "to give (gift), deliver", jyutping: "sung3", topic: "Verbs" },
  { id: 179, chinese: "發", english: "to send (email)", jyutping: "faat3", topic: "Verbs" },
  { id: 180, chinese: "寄", english: "to send (letter)", jyutping: "gei3", topic: "Verbs" },
  { id: 181, chinese: "接", english: "answer phone, pick up", jyutping: "zip3", topic: "Verbs" },
  { id: 182, chinese: "睡覺", english: "to sleep", jyutping: "seoi6 gaau3", topic: "Verbs" },
  { id: 183, chinese: "告訴", english: "to tell", jyutping: "gou3 sou3", topic: "Verbs" },
  { id: 184, chinese: "知道", english: "to know", jyutping: "zi1 dou3", topic: "Verbs" },
  { id: 185, chinese: "認識", english: "to know (be familiar)", jyutping: "jing6 sik1", topic: "Verbs" },
  { id: 186, chinese: "希望", english: "to hope", jyutping: "hei1 mong6", topic: "Verbs" },
  { id: 187, chinese: "開始", english: "to begin", jyutping: "hoi1 ci2", topic: "Verbs" },
  { id: 188, chinese: "覺得", english: "to think, to feel", jyutping: "gok3 dak1", topic: "Verbs", synonym_group: 14 },
  { id: 189, chinese: "参加", english: "to take part in", jyutping: "caam1 gaa1", topic: "Verbs" },
  { id: 190, chinese: "參觀", english: "to visit (places)", jyutping: "caam1 gun1", topic: "Verbs" },
  { id: 191, chinese: "幫助", english: "to help", jyutping: "bong1 zo6", topic: "Verbs" },
  { id: 192, chinese: "回答", english: "to answer, reply", jyutping: "wui4 daap3", topic: "Verbs" },
  { id: 193, chinese: "對 ⋯⋯ 有興趣", english: "to be interested in", jyutping: "deoi3... jau5 hing3 ceoi3", topic: "Verbs" },
  { id: 194, chinese: "愛", english: "to love", jyutping: "oi3", topic: "Verbs" },
  { id: 195, chinese: "喜歡", english: "to like", jyutping: "hei2 fun1", topic: "Verbs" },

  // Topic: Modal verbs
  { id: 196, chinese: "會", english: "can, to be able to", jyutping: "wui6", topic: "Modal verbs" },
  { id: 197, chinese: "想", english: "to plan to, to want", jyutping: "soeng2", topic: "Modal verbs" },
  { id: 198, chinese: "要", english: "would like to, want", jyutping: "jiu3", topic: "Modal verbs" },
  { id: 199, chinese: "能", english: "can, be able to", jyutping: "nang4", topic: "Modal verbs" },
  { id: 200, chinese: "可以", english: "may, can", jyutping: "ho2 ji5", topic: "Modal verbs" },
  { id: 201, chinese: "應該", english: "should", jyutping: "jing1 goi1", topic: "Modal verbs" },

  // Topic: Adjectives
  { id: 202, chinese: "大", english: "big", jyutping: "daai6", topic: "Adjectives" },
  { id: 203, chinese: "小", english: "small", jyutping: "siu2", topic: "Adjectives" },
  { id: 204, chinese: "早", english: "early", jyutping: "zou2", topic: "Adjectives" },
  { id: 205, chinese: "晚", english: "late", jyutping: "maan5", topic: "Adjectives" },
  { id: 206, chinese: "好", english: "good", jyutping: "hou2", topic: "Adjectives" },
  { id: 207, chinese: "壞", english: "bad", jyutping: "waai6", topic: "Adjectives" },
  { id: 208, chinese: "老", english: "old", jyutping: "lou5", topic: "Adjectives" },
  { id: 209, chinese: "舊", english: "old (objects)", jyutping: "gau6", topic: "Adjectives" },
  { id: 210, chinese: "新", english: "new", jyutping: "san1", topic: "Adjectives" },
  { id: 211, chinese: "忙", english: "busy", jyutping: "mong4", topic: "Adjectives" },
  { id: 212, chinese: "累", english: "tired", jyutping: "leoi6", topic: "Adjectives" },
  { id: 213, chinese: "快", english: "fast, quick", jyutping: "faai3", topic: "Adjectives" },
  { id: 214, chinese: "慢", english: "slow", jyutping: "maan6", topic: "Adjectives" },
  { id: 215, chinese: "餓", english: "hungry", jyutping: "ngo6", topic: "Adjectives" },
  { id: 216, chinese: "飽", english: "full", jyutping: "baau2", topic: "Adjectives" },
  { id: 217, chinese: "渴", english: "thirsty", jyutping: "hot3", topic: "Adjectives" },
  { id: 218, chinese: "髒", english: "dirty", jyutping: "zong1", topic: "Adjectives" },
  { id: 219, chinese: "冷", english: "cold", jyutping: "laang5", topic: "Adjectives" },
  { id: 220, chinese: "熱", english: "hot", jyutping: "jit6", topic: "Adjectives" },
  { id: 221, chinese: "對", english: "correct, right", jyutping: "deoi3", topic: "Adjectives" },
  { id: 222, chinese: "錯", english: "incorrect, wrong", jyutping: "co3", topic: "Adjectives" },
  { id: 223, chinese: "遠", english: "far", jyutping: "jyun5", topic: "Adjectives" },
  { id: 224, chinese: "近", english: "near, close", jyutping: "gan6", topic: "Adjectives" },
  { id: 225, chinese: "胖", english: "fat", jyutping: "bun6", topic: "Adjectives", synonym_group: 8 },
  { id: 226, chinese: "肥", english: "fat", jyutping: "fei4", topic: "Adjectives", synonym_group: 8 },
  { id: 227, chinese: "瘦", english: "thin", jyutping: "sau3", topic: "Adjectives" },
  { id: 228, chinese: "高", english: "high, tall", jyutping: "gou1", topic: "Adjectives" },
  { id: 229, chinese: "長", english: "long", jyutping: "coeng4", topic: "Adjectives" },
  { id: 230, chinese: "短", english: "short", jyutping: "dyun2", topic: "Adjectives" },
  { id: 231, chinese: "難", english: "hard, difficult", jyutping: "naan4", topic: "Adjectives" },
  { id: 232, chinese: "容易", english: "easy", jyutping: "jung4 ji6", topic: "Adjectives" },
  { id: 233, chinese: "努力", english: "hardworking", jyutping: "nou5 lik6", topic: "Adjectives" },
  { id: 234, chinese: "舒服", english: "comfortable", jyutping: "syu1 fuk6", topic: "Adjectives" },
  { id: 235, chinese: "高興", english: "pleased, happy", jyutping: "gou1 hing3", topic: "Adjectives", synonym_group: 9 },
  { id: 236, chinese: "快樂", english: "happy", jyutping: "faai3 lok6", topic: "Adjectives", synonym_group: 9 },
  { id: 237, chinese: "開心", english: "happy", jyutping: "hoi1 sam1", topic: "Adjectives", synonym_group: 9 },
  { id: 238, chinese: "好玩兒", english: "interesting, amusing", jyutping: "hou2 wun6 ji4", topic: "Adjectives", synonym_group: 10 },
  { id: 239, chinese: "好吃", english: "delicious", jyutping: "hou2 hek3", topic: "Adjectives" },
  { id: 240, chinese: "生氣", english: "angry", jyutping: "sang1 hei3", topic: "Adjectives" },
  { id: 241, chinese: "安靜", english: "quiet", jyutping: "on1 zing6", topic: "Adjectives" },
  { id: 242, chinese: "漂亮", english: "beautiful", jyutping: "piu3 loeng6", topic: "Adjectives" },
  { id: 243, chinese: "可愛", english: "lovely, loveable", jyutping: "ho2 oi3", topic: "Adjectives" },
  { id: 244, chinese: "健康", english: "healthy", jyutping: "gin6 hong1", topic: "Adjectives" },
  { id: 245, chinese: "乾淨", english: "clean", jyutping: "gon1 zing6", topic: "Adjectives" },
  { id: 246, chinese: "有趣", english: "funny, interesting", jyutping: "jau5 ceoi3", topic: "Adjectives", synonym_group: 10 },
  { id: 247, chinese: "有意思", english: "interesting", jyutping: "jau5 ji3 si3", topic: "Adjectives", synonym_group: 10 },
  { id: 248, chinese: "沒意思", english: "boring", jyutping: "mut6 ji3 si3", topic: "Adjectives" },
  { id: 249, chinese: "有用", english: "useful", jyutping: "jau5 jung6", topic: "Adjectives" },
  { id: 250, chinese: "有錢", english: "rich", jyutping: "jau5 cin4", topic: "Adjectives" },
  { id: 251, chinese: "一樣", english: "same", jyutping: "jat1 joeng6", topic: "Adjectives" },

  // Topic: Adverbs
  { id: 252, chinese: "不", english: "no", jyutping: "bat1", topic: "Adverbs" },
  { id: 253, chinese: "沒(有)", english: "not (have)", jyutping: "mut6 (jau5)", topic: "Adverbs" },
  { id: 254, chinese: "很", english: "very", jyutping: "han2", topic: "Adverbs" },
  { id: 255, chinese: "也", english: "also, too", jyutping: "jaa5", topic: "Adverbs" },
  { id: 256, chinese: "都", english: "both, all", jyutping: "dou1", topic: "Adverbs" },
  { id: 257, chinese: "再", english: "again", jyutping: "zoi3", topic: "Adverbs" },
  { id: 258, chinese: "還", english: "still, yet, also", jyutping: "waan4", topic: "Adverbs" },
  { id: 259, chinese: "更", english: "even more", jyutping: "gang3", topic: "Adverbs" },
  { id: 260, chinese: "當然", english: "certainly, of course", jyutping: "dong1 jin4", topic: "Adverbs" },

  // Topic: Question words
  { id: 261, chinese: "嗎", english: "question particle", jyutping: "maa1", topic: "Question words" },
  { id: 262, chinese: "呢", english: "modal particle", jyutping: "ne1", topic: "Question words" },
  { id: 263, chinese: "吧", english: "modal particle", jyutping: "baa6", topic: "Question words" },
  { id: 264, chinese: "還是……？", english: "or...?", jyutping: "waan4 si6", topic: "Question words" },
  { id: 265, chinese: "什麼", english: "what", jyutping: "sam6 mo1", topic: "Question words" },
  { id: 266, chinese: "誰", english: "who", jyutping: "seoi4", topic: "Question words" },
  { id: 267, chinese: "哪", english: "which", jyutping: "naa5", topic: "Question words" },
  { id: 268, chinese: "哪兒", english: "where", jyutping: "naa5 ji4", topic: "Question words" },
  { id: 269, chinese: "為什麼", english: "why", jyutping: "wai6 sam6 mo1", topic: "Question words" },
  { id: 270, chinese: "什麼時候", english: "when", jyutping: "sam6 mo1 si4 hau6", topic: "Question words" },
  { id: 271, chinese: "幾", english: "how many", jyutping: "gei2", topic: "Question words" },
  { id: 272, chinese: "多少", english: "how many/much", jyutping: "do1 siu2", topic: "Question words" },
  { id: 273, chinese: "幾點", english: "what time", jyutping: "gei2 dim2", topic: "Question words" },
  { id: 274, chinese: "怎麼", english: "how?", jyutping: "zam2 mo1", topic: "Question words" },
  { id: 275, chinese: "怎麼樣", english: "how is...", jyutping: "zam2 mo1 joeng6", topic: "Question words" },

  // Topic: Locations
  { id: 276, chinese: "這裡", english: "here", jyutping: "ze3 leoi5", topic: "Locations", synonym_group: 11 },
  { id: 277, chinese: "這兒", english: "here", jyutping: "ze3 ji4", topic: "Locations", synonym_group: 11 },
  { id: 278, chinese: "那裡", english: "there", jyutping: "naa5 leoi5", topic: "Locations", synonym_group: 12 },
  { id: 279, chinese: "那兒", english: "there", jyutping: "naa5 ji4", topic: "Locations", synonym_group: 12 },
  { id: 280, chinese: "左", english: "left", jyutping: "zo2", topic: "Locations" },
  { id: 281, chinese: "右", english: "right", jyutping: "jau6", topic: "Locations" },
  { id: 282, chinese: "前(邊)", english: "in front of", jyutping: "cin4 (bin1)", topic: "Locations" },
  { id: 283, chinese: "後(邊)", english: "behind", jyutping: "hau6 (bin1)", topic: "Locations" },
  { id: 284, chinese: "中間(兒)", english: "middle", jyutping: "zung1 gaan1 (ji4)", topic: "Locations" },
  { id: 285, chinese: "對面", english: "opposite", jyutping: "deoi3 min6", topic: "Locations" },
  { id: 286, chinese: "附近", english: "nearby", jyutping: "fu6 gin6", topic: "Locations" },
  { id: 287, chinese: "在……之間", english: "in between...", jyutping: "zoi6...zi1 gaan1", topic: "Locations" },
  { id: 288, chinese: "離", english: "away from", jyutping: "lei4", topic: "Locations" },
  { id: 289, chinese: "往", english: "towards", jyutping: "wong5", topic: "Locations" },

  // Topic: Connecting words
  { id: 290, chinese: "和", english: "and", jyutping: "wo4", topic: "Connecting words" },
  { id: 291, chinese: "然後", english: "then, afterwards", jyutping: "jin4 hau6", topic: "Connecting words" },
  { id: 292, chinese: "因為", english: "because", jyutping: "jan1 wai6", topic: "Connecting words" },
  { id: 293, chinese: "所以", english: "so, therefore", jyutping: "so2 ji5", topic: "Connecting words" },
  { id: 294, chinese: "雖然", english: "although", jyutping: "seoi1 jin4", topic: "Connecting words" },
  { id: 295, chinese: "可是", english: "but, however", jyutping: "ho2 si6", topic: "Connecting words", synonym_group: 13 },
  { id: 296, chinese: "但是", english: "but, however", jyutping: "daan6 si6", topic: "Connecting words", synonym_group: 13 },
  { id: 297, chinese: "一邊(兒)……一邊(兒)", english: "while...", jyutping: "jat1 bin1...", topic: "Connecting words" },
  { id: 298, chinese: "比", english: "(comparative) than", jyutping: "bei2", topic: "Connecting words" },
  { id: 299, chinese: "越…越", english: "the more...the more", jyutping: "jyut6... jyut6", topic: "Connecting words" },
  { id: 300, chinese: "越來越", english: "more and more", jyutping: "jyut6 loi4 jyut6", topic: "Connecting words" },
  { id: 301, chinese: "又……又……", english: "not only...but also...", jyutping: "jau6... jau6...", topic: "Connecting words" },

  // Topic: Social
  { id: 302, chinese: "你好", english: "hello", jyutping: "nei5 hou2", topic: "Social" },
  { id: 303, chinese: "大家好", english: "hello everyone", jyutping: "daai6 gaa1 hou2", topic: "Social" },
  { id: 304, chinese: "晚上好", english: "good evening", jyutping: "maan5 soeng6 hou2", topic: "Social" },
  { id: 305, chinese: "晚安", english: "good night", jyutping: "maan5 on1", topic: "Social" },
  { id: 306, chinese: "再見", english: "goodbye", jyutping: "zoi3 gin3", topic: "Social" },
  { id: 307, chinese: "明天見", english: "see you tomorrow", jyutping: "ming4 tin1 gin3", topic: "Social" },
  { id: 308, chinese: "請問", english: "excuse me", jyutping: "cing2 man6", topic: "Social" },
  { id: 309, chinese: "謝謝", english: "thank you", jyutping: "ze6 ze6", topic: "Social" },
  { id: 310, chinese: "對不起", english: "sorry", jyutping: "deoi3 bat1 hei2", topic: "Social" },
  { id: 311, chinese: "沒關係", english: "it doesn't matter", jyutping: "mut6 gwaan1 hai6", topic: "Social" },

  // Topic: Abbreviations
  { id: 312, chinese: "中學會考", english: "GCSE", jyutping: "zung1 hok6 wui6 haau2", topic: "Abbreviations" },
  { id: 313, chinese: "高等程度會考", english: "A Levels", jyutping: "gou1 dang2 cing4 dou6 wui6 haau2", topic: "Abbreviations" },
  { id: 314, chinese: "CD", english: "CD", jyutping: "CD", topic: "Abbreviations" },
  { id: 315, chinese: "DVD", english: "DVD", jyutping: "DVD", topic: "Abbreviations" },
  { id: 316, chinese: "MP3", english: "MP3", jyutping: "MP3", topic: "Abbreviations" },
  { id: 317, chinese: "iPad", english: "iPad", jyutping: "iPad", topic: "Abbreviations" },
  { id: 318, chinese: "U盤", english: "USB", jyutping: "U pun4", topic: "Abbreviations" },

  // Topic: Others
  { id: 319, chinese: "的", english: "structure particle", jyutping: "dik1", topic: "Others" },
  { id: 320, chinese: "地", english: "adverbial marker", jyutping: "dei6", topic: "Others" },
  { id: 321, chinese: "得", english: "complement marker", jyutping: "dak1", topic: "Others" },
  { id: 322, chinese: "最", english: "the most", jyutping: "zeoi3", topic: "Others" },
  { id: 323, chinese: "每", english: "every", jyutping: "mui5", topic: "Others" },
  { id: 324, chinese: "第", english: "prefix (ordinal)", jyutping: "dai6", topic: "Others" },
  { id: 325, chinese: "太太", english: "Mrs", jyutping: "taai3 taai3", topic: "Others" },
  { id: 326, chinese: "小姐", english: "Miss", jyutping: "siu2 ze2", topic: "Others" },
  { id: 327, chinese: "先生", english: "Mr, Sir", jyutping: "sin1 sang1", topic: "Others" },
  { id: 328, chinese: "一點兒", english: "a bit", jyutping: "jat1 dim2 ji4", topic: "Others" },
  { id: 329, chinese: "些/一些", english: "some", jyutping: "se1/ jat1 se1", topic: "Others" },
  { id: 330, chinese: "號碼", english: "number", jyutping: "hou6 maa5", topic: "Others" },
  { id: 331, chinese: "東西", english: "thing", jyutping: "dung1 sai1", topic: "Others" },
  { id: 332, chinese: "事情", english: "matter", jyutping: "si6 cing4", topic: "Others" },
  { id: 333, chinese: "一直走", english: "go straight on", jyutping: "jat1 zik6 zau2", topic: "Others" },
  { id: 334, chinese: "下一個", english: "the next", jyutping: "haa5 jat1 go3", topic: "Others" },
  { id: 335, chinese: "還可以", english: "okay, alright", jyutping: "waan4 ho2 ji5", topic: "Others" },
  { id: 336, chinese: "差不多", english: "almost", jyutping: "caa1 bat1 do1", topic: "Others" },
  { id: 337, chinese: "不錯", english: "quite good", jyutping: "bat1 co3", topic: "Others" },
  { id: 338, chinese: "非常", english: "extremely", jyutping: "fei1 soeng4", topic: "Others" },
  { id: 339, chinese: "太……了", english: "too...", jyutping: "taai3...liu5", topic: "Others" },
  { id: 340, chinese: "……極了", english: "extremely...", jyutping: "...gik6 liu5", topic: "Others" },
  { id: 341, chinese: "先……再……", english: "first...then...", jyutping: "sin1...zoi3...", topic: "Others" },
  { id: 342, chinese: "跟/和……一起", english: "together with...", jyutping: "gan1/ wo4... jat1 hei2", topic: "Others" },
  { id: 343, chinese: "快要……了", english: "to be about to...", jyutping: "faai3 jiu3...liu5", topic: "Others" },
  { id: 344, chinese: "可能", english: "perhaps, possibly", jyutping: "ho2 nang4", topic: "Others" },
  { id: 345, chinese: "正在", english: "process of doing", jyutping: "zing3 zoi6", topic: "Others" },
  { id: 346, chinese: "為了 ⋯", english: "in order to...", jyutping: "wai6 liu5...", topic: "Others" },
  { id: 347, chinese: "我認為", english: "in my opinion", jyutping: "ngo5 jing6 wai4", topic: "Others" },
  { id: 348, chinese: "我覺得", english: "I think, I feel", jyutping: "ngo5 gok3 dak1", topic: "Others", synonym_group: 14 },

  // ==========================================
  // List 2: Topic-related vocabulary
  // ==========================================

  // Topic Area A: Town & Rural
  { id: 349, chinese: "地方", english: "place", jyutping: "dei6 fong1", topic: "Town & Rural" },
  { id: 350, chinese: "城市", english: "city", jyutping: "sing4 si5", topic: "Town & Rural" },
  { id: 351, chinese: "市中心", english: "city centre", jyutping: "si5 zung1 sam1", topic: "Town & Rural" },
  { id: 352, chinese: "郊區", english: "suburb", jyutping: "gaau1 keoi1", topic: "Town & Rural" },
  
  { id: 353, chinese: "路", english: "road, route, bus number", jyutping: "lou6", topic: "Town & Rural" },
  { id: 354, chinese: "北京", english: "Beijing", jyutping: "bak1 ging1", topic: "Town & Rural" },
  { id: 355, chinese: "上海", english: "Shanghai", jyutping: "soeng6 hoi2", topic: "Town & Rural" },
  { id: 356, chinese: "廣州", english: "Guangzhou", jyutping: "gwong2 zau1", topic: "Town & Rural" },
  { id: 357, chinese: "香港", english: "Hong Kong", jyutping: "hoeng1 gong2", topic: "Town & Rural" },
  { id: 358, chinese: "台灣", english: "Taiwan", jyutping: "toi4 waan1", topic: "Town & Rural" },
  { id: 359, chinese: "倫敦", english: "London", jyutping: "leon4 deon1", topic: "Town & Rural" },
  { id: 360, chinese: "工廠", english: "factory", jyutping: "gung1 cong2", topic: "Town & Rural" },
  { id: 361, chinese: "橋", english: "bridge", jyutping: "kiu4", topic: "Town & Rural" },
  { id: 362, chinese: "方便", english: "convenient", jyutping: "fong1 bin6", topic: "Town & Rural" },

  // Topic Area A: Holidays
  { id: 363, chinese: "放假", english: "to be on holiday", jyutping: "fong3 gaa3", topic: "Holidays" },
  { id: 364, chinese: "假期", english: "holiday", jyutping: "gaa3 kei4", topic: "Holidays" },
  { id: 365, chinese: "旅遊", english: "to travel, tourism", jyutping: "leoi5 jau4", topic: "Holidays" },
  { id: 366, chinese: "訂", english: "to book (tickets/hotel)", jyutping: "ding6", topic: "Holidays" },
  { id: 367, chinese: "飯店", english: "hotel", jyutping: "faan6 dim3", topic: "Holidays", synonym_group: 21 },
  { id: 368, chinese: "酒店", english: "hotel", jyutping: "zau2 dim3", topic: "Holidays", synonym_group: 21 },
  { id: 369, chinese: "服務員", english: "attendant", jyutping: "fuk6 mou6 jyun4", topic: "Holidays" },
  { id: 370, chinese: "問題", english: "question, problem", jyutping: "man6 tai4", topic: "Holidays" },
  { id: 371, chinese: "空調", english: "air-conditioning", jyutping: "hung1 tiu4", topic: "Holidays" },
  { id: 372, chinese: "房間", english: "room", jyutping: "fong4 gaan1", topic: "Holidays" },
  { id: 373, chinese: "廁所", english: "toilet", jyutping: "ci3 so2", topic: "Holidays", synonym_group: 22 },
  { id: 374, chinese: "洗手間", english: "toilet", jyutping: "sai2 sau2 gaan1", topic: "Holidays", synonym_group: 22 },
  { id: 375, chinese: "電視", english: "TV", jyutping: "din6 si6", topic: "Holidays" },
  { id: 376, chinese: "游泳池", english: "swimming pool", jyutping: "jau4 wing6 ci4", topic: "Holidays" },
  { id: 377, chinese: "廣場", english: "square", jyutping: "gwong2 coeng4", topic: "Holidays" },
  { id: 378, chinese: "入口", english: "entrance", jyutping: "jap6 hau2", topic: "Holidays" },
  { id: 379, chinese: "出口", english: "exit", jyutping: "ceot1 hau2", topic: "Holidays" },
  { id: 380, chinese: "地圖", english: "map", jyutping: "dei6 tou4", topic: "Holidays" },
  { id: 381, chinese: "行李", english: "luggage", jyutping: "hang4 lei5", topic: "Holidays" },
  { id: 382, chinese: "照相機", english: "camera", jyutping: "ziu3 soeng2 gei1", topic: "Holidays" },
  { id: 383, chinese: "護照", english: "passport", jyutping: "wu6 ziu3", topic: "Holidays" },
  { id: 384, chinese: "紀念品", english: "souvenir", jyutping: "gei2 nim6 ban2", topic: "Holidays" },
  { id: 385, chinese: "明信片", english: "postcard", jyutping: "ming4 seon3 pin2", topic: "Holidays" },
  { id: 386, chinese: "風景", english: "scenery", jyutping: "fung1 ging2", topic: "Holidays" },
  { id: 387, chinese: "禮物", english: "present, gift", jyutping: "lai5 mat6", topic: "Holidays" },

  // Topic Area A: Services
  { id: 388, chinese: "銀行", english: "bank", jyutping: "ngan4 hong4", topic: "Services" },
  { id: 389, chinese: "博物館", english: "museum", jyutping: "bok3 mat6 gun2", topic: "Services" },
  { id: 390, chinese: "體育館", english: "gym", jyutping: "tai2 juk6 gun2", topic: "Services" },
  { id: 391, chinese: "醫院", english: "hospital", jyutping: "ji1 jyun2", topic: "Services" },
  { id: 392, chinese: "電影院", english: "cinema", jyutping: "din6 jing2 jyun2", topic: "Services" },
  { id: 393, chinese: "警察局", english: "police station", jyutping: "ging2 caat3 guk2", topic: "Services" },
  { id: 394, chinese: "郵局", english: "post office", jyutping: "jau4 guk2", topic: "Services" },
  { id: 395, chinese: "郵票", english: "stamp", jyutping: "jau4 piu3", topic: "Services" },
  { id: 396, chinese: "小吃店", english: "snack bar", jyutping: "siu2 hek3 dim3", topic: "Services" },
  { id: 397, chinese: "快餐店", english: "fast food restaurant", jyutping: "faai3 caan1 dim3", topic: "Services" },
  { id: 398, chinese: "公園", english: "park", jyutping: "gung1 jyun2", topic: "Services" },
  { id: 399, chinese: "動物園", english: "zoo", jyutping: "dung6 mat6 jyun4", topic: "Services" },

  // Topic Area A: Customs & Traditions
  { id: 400, chinese: "廟", english: "temple", jyutping: "miu6", topic: "Customs" },
  { id: 401, chinese: "教堂", english: "church", jyutping: "gaau3 tong2", topic: "Customs" },
  { id: 402, chinese: "生日", english: "birthday", jyutping: "saang1 jat6", topic: "Customs" },
  { id: 403, chinese: "聖誕快樂", english: "Happy Christmas", jyutping: "sing3 daan3 faai3 lok6", topic: "Customs" },
  { id: 404, chinese: "慶祝", english: "to celebrate", jyutping: "hing3 zuk1", topic: "Customs" },
  { id: 405, chinese: "復活節", english: "Easter", jyutping: "fuk6 wut6 zit3", topic: "Customs" },
  { id: 406, chinese: "耶誕節", english: "Christmas", jyutping: "je4 daan3 zit3", topic: "Customs" },
  { id: 407, chinese: "節日", english: "Festival", jyutping: "zit3 jat6", topic: "Customs" },
  { id: 408, chinese: "紅包", english: "red pocket", jyutping: "hung4 baau1", topic: "Customs" },
  { id: 409, chinese: "傳統的", english: "traditional", jyutping: "cyun4 tung2 dik1", topic: "Customs" },
  { id: 410, chinese: "習慣", english: "habit", jyutping: "zaap6 gwaan3", topic: "Customs" },
  { id: 411, chinese: "風箏", english: "kite", jyutping: "fung1 zang1", topic: "Traditions" },
  { id: 412, chinese: "筷子", english: "chopsticks", jyutping: "faai3 zi2", topic: "Traditions" },
  { id: 413, chinese: "書法", english: "calligraphy", jyutping: "syu1 faat3", topic: "Traditions" },
  { id: 414, chinese: "國畫", english: "Chinese painting", jyutping: "gwok3 waa2", topic: "Traditions" },
  { id: 415, chinese: "毛筆", english: "Chinese brush", jyutping: "mou4 bat1", topic: "Traditions" },
  { id: 416, chinese: "春節", english: "Spring Festival", jyutping: "ceon1 zit3", topic: "Traditions", synonym_group: 23 },
  { id: 417, chinese: "中國新年", english: "Chinese New Year", jyutping: "zung1 gwok3 san1 nin4", topic: "Traditions", synonym_group: 23 },
  { id: 418, chinese: "端午節", english: "Dragon Boat Festival", jyutping: "dyun1 ng5 zit3", topic: "Traditions", synonym_group: 24 },
  { id: 419, chinese: "龍舟節", english: "Dragon Boat Festival", jyutping: "lung4 zau1 zit3", topic: "Traditions", synonym_group: 24 },
  { id: 420, chinese: "龍舟", english: "dragon boat", jyutping: "lung4 zau1", topic: "Traditions" },
  { id: 421, chinese: "中秋節", english: "Mid-Autumn Festival", jyutping: "zung1 cau1 zit3", topic: "Traditions" },
  { id: 422, chinese: "舞龍", english: "dragon dance", jyutping: "mou5 lung4", topic: "Traditions" },
  { id: 423, chinese: "舞獅", english: "lion dance", jyutping: "mou5 si1", topic: "Traditions" },

  // Topic Area B: School Life & Rules
  // ADDED: School & Student
  { id: 424, chinese: "學校", english: "school", jyutping: "hok6 haau6", topic: "School Life" },
  { id: 425, chinese: "小學", english: "primary school", jyutping: "siu2 hok6", topic: "School Life" },
  { id: 426, chinese: "中學", english: "secondary school", jyutping: "zung1 hok6", topic: "School Life" },
  { id: 427, chinese: "大學", english: "university", jyutping: "daai6 hok6", topic: "School Life" },
  { id: 428, chinese: "學生", english: "student", jyutping: "hok6 saang1", topic: "School Life" },
  { id: 429, chinese: "同學", english: "classmate", jyutping: "tung4 hok6", topic: "School Life" },
  { id: 430, chinese: "學期", english: "school term", jyutping: "hok6 kei4", topic: "School Life" },
  { id: 431, chinese: "起床", english: "get up", jyutping: "hei2 cong4", topic: "School Life" },
  { id: 432, chinese: "上學", english: "to go to school", jyutping: "soeng5 hok6", topic: "School Life" },
  { id: 433, chinese: "上課", english: "to attend class", jyutping: "soeng5 fo3", topic: "School Life" },
  { id: 434, chinese: "作業", english: "homework", jyutping: "zok3 jip6", topic: "School Life", synonym_group: 20 },
  // ADDED: Homework (Group 20)
  { id: 435, chinese: "功課", english: "homework", jyutping: "gung1 fo3", topic: "School Life", synonym_group: 20 },
  { id: 436, chinese: "課本", english: "textbook", jyutping: "fo3 bun2", topic: "School Life" },
  { id: 437, chinese: "數學", english: "maths", jyutping: "sou3 hok6", topic: "School Life" },
  { id: 438, chinese: "科學", english: "science", jyutping: "fo1 hok6", topic: "School Life" },
  { id: 439, chinese: "體育", english: "P.E.", jyutping: "tai2 juk6", topic: "School Life" },
  { id: 440, chinese: "歷史", english: "history", jyutping: "lik6 si2", topic: "School Life" },
  { id: 441, chinese: "地理", english: "geography", jyutping: "dei6 lei5", topic: "School Life" },
  { id: 442, chinese: "音樂", english: "music", jyutping: "jam1 ngok6", topic: "School Life" },
  { id: 443, chinese: "美術", english: "art", jyutping: "mei5 seot6", topic: "School Life", synonym_group: 29 },
  { id: 444, chinese: "藝術", english: "art", jyutping: "ngai6 seot6", topic: "School Life", synonym_group: 29 },
  { id: 445, chinese: "戲劇", english: "drama", jyutping: "hei3 kek6", topic: "School Life" },
  { id: 446, chinese: "教室", english: "classroom", jyutping: "gaau3 sat1", topic: "School Life", synonym_group: 19 },
  // ADDED: Classroom (Group 19)
  { id: 447, chinese: "課室", english: "classroom", jyutping: "fo3 sat1", topic: "School Life", synonym_group: 19 },
  { id: 448, chinese: "禮堂", english: "assembly hall", jyutping: "lai5 tong4", topic: "School Life" },
  { id: 449, chinese: "運動場", english: "sports ground", jyutping: "wan6 dung6 coeng4", topic: "School Life" },
  { id: 450, chinese: "書", english: "book", jyutping: "syu1", topic: "School Life" },
  { id: 451, chinese: "筆", english: "pen", jyutping: "bat1", topic: "School Life" },
  { id: 452, chinese: "字典", english: "dictionary", jyutping: "zi6 din2", topic: "School Rules", synonym_group: 41 },
  { id: 453, chinese: "交換", english: "exchange", jyutping: "gaau1 wun6", topic: "School Rules" },
  { id: 454, chinese: "校長", english: "head teacher", jyutping: "haau6 zoeng2", topic: "School Rules" },
  { id: 455, chinese: "壓力", english: "pressure", jyutping: "aat3 lik6", topic: "School Rules" },
  { id: 456, chinese: "成績", english: "results, marks", jyutping: "sing4 zik1", topic: "School Rules" },
  { id: 457, chinese: "規則", english: "rule", jyutping: "gwai1 zak1", topic: "School Rules" },
  { id: 458, chinese: "校服", english: "school uniform", jyutping: "haau6 fuk6", topic: "School Rules" },
  { id: 459, chinese: "教師", english: "teacher", jyutping: "gaau3 si1", topic: "School Rules", synonym_group: 18 },
  // ADDED: Teacher (Group 18)
  { id: 460, chinese: "老師", english: "teacher", jyutping: "lou5 si1", topic: "School Rules", synonym_group: 18 },
  { id: 461, chinese: "生物", english: "Biology", jyutping: "sang1 mat6", topic: "School Rules" },
  { id: 462, chinese: "化學", english: "Chemistry", jyutping: "faa3 hok6", topic: "School Rules" },
  { id: 463, chinese: "文章", english: "essay", jyutping: "man4 zoeng1", topic: "School Rules" },
  { id: 464, chinese: "畢業", english: "graduate", jyutping: "bat1 jip6", topic: "School Rules" },
  { id: 465, chinese: "分數", english: "mark, grade", jyutping: "fan1 sou3", topic: "School Rules" },
  { id: 466, chinese: "物理", english: "physics", jyutping: "mat6 lei5", topic: "School Rules" },
  { id: 467, chinese: "留學生", english: "student studying abroad", jyutping: "lau4 hok6 saang1", topic: "School Trips" },
  { id: 468, chinese: "時間表", english: "timetable", jyutping: "si4 gaan1 biu2", topic: "School Trips" },
  { id: 469, chinese: "用心", english: "to pay attention", jyutping: "jung6 sam1", topic: "School Trips" },
  { id: 470, chinese: "暑假", english: "summer holiday", jyutping: "syu2 gaa3", topic: "School Trips" },
  { id: 471, chinese: "打算", english: "plan, intention", jyutping: "daa2 syun3", topic: "School Trips" },
  { id: 472, chinese: "高考", english: "GCE equivalent", jyutping: "gou1 haau2", topic: "School Trips" },
  { id: 473, chinese: "計畫", english: "plan", jyutping: "gai3 waak6", topic: "School Trips" },

  // Topic Area B: Work & Future
  { id: 474, chinese: "工作", english: "job, work", jyutping: "gung1 zok3", topic: "Work" },
  { id: 475, chinese: "工資", english: "salary", jyutping: "gung1 zi1", topic: "Work" },
  { id: 476, chinese: "廚師", english: "cook, chef", jyutping: "cyu4 si1", topic: "Work" },
  { id: 477, chinese: "司機", english: "driver", jyutping: "si1 gei1", topic: "Work" },
  { id: 478, chinese: "記者", english: "journalist", jyutping: "gei3 ze2", topic: "Work" },
  { id: 479, chinese: "演員", english: "actor/actress", jyutping: "jin2 jyun4", topic: "Work" },
  { id: 480, chinese: "歌星", english: "singer", jyutping: "go1 sing1", topic: "Work" },
  { id: 481, chinese: "經理", english: "manager", jyutping: "ging1 lei5", topic: "Work" },
  { id: 482, chinese: "科學家", english: "scientist", jyutping: "fo1 hok6 gaa1", topic: "Work" },
  { id: 483, chinese: "工程師", english: "engineer", jyutping: "gung1 cing4 si1", topic: "Work" },
  { id: 484, chinese: "作家", english: "writer", jyutping: "zok3 gaa1", topic: "Work" },
  { id: 485, chinese: "商人", english: "businessman", jyutping: "soeng1 jan4", topic: "Work" },
  { id: 486, chinese: "工人", english: "worker", jyutping: "gung1 jan4", topic: "Work" },
  { id: 487, chinese: "做生意", english: "do business", jyutping: "zou6 saang1 ji3", topic: "Work" },
  { id: 488, chinese: "醫生", english: "doctor", jyutping: "ji1 sang1", topic: "Work", synonym_group: 25 },
  { id: 489, chinese: "大夫", english: "doctor", jyutping: "daai6 fu1", topic: "Work", synonym_group: 25 },
  { id: 490, chinese: "護士", english: "nurse", jyutping: "wu6 si6", topic: "Work" },
  { id: 491, chinese: "訪問", english: "interview", jyutping: "fong2 man6", topic: "Work", synonym_group: 26 },
  { id: 492, chinese: "採訪", english: "interview", jyutping: "coi2 fong2", topic: "Work", synonym_group: 26 },
  { id: 493, chinese: "上班", english: "go to work", jyutping: "soeng5 baan1", topic: "Work" },
  { id: 494, chinese: "下班", english: "finish work", jyutping: "haa6 baan1", topic: "Work" },
  { id: 495, chinese: "申請", english: "to apply", jyutping: "san1 cing2", topic: "Work" },
  { id: 496, chinese: "訓練", english: "training", jyutping: "fan3 lin6", topic: "Work" },
  { id: 497, chinese: "兼職", english: "part time", jyutping: "gim1 zik1", topic: "Work" },
  { id: 498, chinese: "全職", english: "full time", jyutping: "cyun4 zik1", topic: "Work" },
  { id: 499, chinese: "志願者", english: "volunteer", jyutping: "zi3 jyun6 ze2", topic: "Work", synonym_group: 27 },
  { id: 500, chinese: "義工", english: "volunteer", jyutping: "ji6 gung1", topic: "Work", synonym_group: 27 },
  { id: 501, chinese: "賺錢", english: "to earn money", jyutping: "zaan6 cin2", topic: "Future Plans" },
  { id: 502, chinese: "公司", english: "company", jyutping: "gung1 si1", topic: "Future Plans" },
  { id: 503, chinese: "零用錢", english: "pocket money", jyutping: "ling4 jung6 cin2", topic: "Future Plans", synonym_group: 35 },

  // Topic Area C: Home & Daily Life
  { id: 504, chinese: "房子", english: "house", jyutping: "fong4 zi2", topic: "Home" },
  { id: 505, chinese: "樓", english: "building, floor", jyutping: "lau4", topic: "Home" },
  { id: 506, chinese: "花園", english: "garden", jyutping: "faa1 jyun2", topic: "Home" },
  { id: 507, chinese: "廚房", english: "kitchen", jyutping: "cyu4 fong2", topic: "Home" },
  { id: 508, chinese: "飯廳", english: "dining room", jyutping: "faan6 teng1", topic: "Home" },
  { id: 509, chinese: "臥室", english: "bedroom", jyutping: "ngo6 sat1", topic: "Home" },
  { id: 510, chinese: "客廳", english: "sitting room", jyutping: "haak3 teng1", topic: "Home" },
  { id: 511, chinese: "沙發", english: "sofa", jyutping: "saa1 faat3", topic: "Home" },
  { id: 512, chinese: "冰箱", english: "fridge", jyutping: "bing1 soeng1", topic: "Home" },
  { id: 513, chinese: "桌子", english: "table", jyutping: "coek3 zi2", topic: "Home" },
  { id: 514, chinese: "椅子", english: "chair", jyutping: "ji2 zi2", topic: "Home" },
  { id: 515, chinese: "衣櫃", english: "wardrobe", jyutping: "ji1 gwai6", topic: "Home" },
  { id: 516, chinese: "書架", english: "bookshelf", jyutping: "syu1 gaa2", topic: "Home" },
  { id: 517, chinese: "燈", english: "light, lamp", jyutping: "dang1", topic: "Home" },
  { id: 518, chinese: "門", english: "door", jyutping: "mun4", topic: "Home" },
  { id: 519, chinese: "鐘", english: "clock", jyutping: "zung1", topic: "Home" },
  { id: 520, chinese: "貓", english: "cat", jyutping: "maau1", topic: "Daily Routine" },
  { id: 521, chinese: "鳥", english: "bird", jyutping: "niu5", topic: "Daily Routine" },
  { id: 522, chinese: "寵物", english: "pet", jyutping: "cung2 mat6", topic: "Daily Routine" },
  { id: 523, chinese: "家務", english: "housework", jyutping: "gaa1 mou6", topic: "Daily Routine" },
  { id: 524, chinese: "做飯", english: "to cook", jyutping: "zou6 faan6", topic: "Daily Routine" },
  { id: 525, chinese: "打掃", english: "clean", jyutping: "daa2 sou3", topic: "Daily Routine" },
  { id: 526, chinese: "廣告", english: "adverts", jyutping: "gwong2 gou3", topic: "Role Models" },
  { id: 527, chinese: "偶像", english: "idol", jyutping: "ngau5 zoeng6", topic: "Role Models" },
  { id: 528, chinese: "歌", english: "song", jyutping: "go1", topic: "Role Models" },
  { id: 529, chinese: "有名", english: "famous", jyutping: "jau5 meng2", topic: "Role Models", synonym_group: 36 },
  { id: 530, chinese: "著名", english: "famous", jyutping: "zyu3 ming4", topic: "Role Models", synonym_group: 36 },
  { id: 531, chinese: "足球運動員", english: "footballer", jyutping: "zuk1 kau4 wan6 dung6 jyun4", topic: "Role Models" },
  { id: 532, chinese: "榜樣", english: "role model", jyutping: "bong2 joeng6", topic: "Role Models" },
  { id: 533, chinese: "報紙", english: "newspaper", jyutping: "bou3 zi2", topic: "Role Models" },
  { id: 534, chinese: "雜誌", english: "magazine", jyutping: "zaap6 zi3", topic: "Role Models" },
  { id: 535, chinese: "明星", english: "celebrities", jyutping: "ming4 sing1", topic: "Role Models" },

  // Topic Area C: Family & Childhood
  { id: 536, chinese: "媽媽", english: "mother", jyutping: "maa4 maa1", topic: "Family" },
  { id: 537, chinese: "哥哥", english: "elder brother", jyutping: "go4 go1", topic: "Family" },
  { id: 538, chinese: "姐姐", english: "elder sister", jyutping: "ze4 ze1", topic: "Family" },
  { id: 539, chinese: "弟弟", english: "younger brother", jyutping: "dai4 dai6", topic: "Family" },
  { id: 540, chinese: "妹妹", english: "younger sister", jyutping: "mui4 mui2", topic: "Family" },
  { id: 541, chinese: "父母", english: "parents", jyutping: "fu6 mou5", topic: "Family" },
  { id: 542, chinese: "自己", english: "self", jyutping: "zi6 gei2", topic: "Family" },
  { id: 543, chinese: "介紹", english: "introduce", jyutping: "gaai3 siu6", topic: "Family" },
  { id: 544, chinese: "名字", english: "name", jyutping: "ming4 zi6", topic: "Family" },
  { id: 545, chinese: "姓名", english: "full name", jyutping: "sing3 ming4", topic: "Family" },
  { id: 546, chinese: "年齡", english: "age", jyutping: "nin4 ling4", topic: "Family" },
  { id: 547, chinese: "年", english: "year", jyutping: "nin4", topic: "Family" },
  { id: 548, chinese: "出生", english: "to be born", jyutping: "ceot1 sang1", topic: "Family" },
  { id: 549, chinese: "地點", english: "place, venue", jyutping: "dei6 dim2", topic: "Family" },
  { id: 550, chinese: "朋友", english: "friend", jyutping: "pang4 jau5", topic: "Family" },
  { id: 551, chinese: "年輕人", english: "young people", jyutping: "nin4 hing1 jan4", topic: "Family" },
  { id: 552, chinese: "老年人", english: "elderly people", jyutping: "lou5 nin4 jan4", topic: "Family" },
  { id: 553, chinese: "頭髮", english: "hair", jyutping: "tau4 faat3", topic: "Family" },
  { id: 554, chinese: "眼睛", english: "eye", jyutping: "ngaan5 zing1", topic: "Family" },
  { id: 555, chinese: "眼鏡", english: "glasses", jyutping: "ngaan5 geng2", topic: "Family" },
  { id: 556, chinese: "個子", english: "height", jyutping: "go3 zi2", topic: "Family" },
  { id: 557, chinese: "衣服", english: "clothes", jyutping: "ji1 fuk6", topic: "Family" },
  { id: 558, chinese: "鞋", english: "shoes", jyutping: "haai4", topic: "Family" },
  { id: 559, chinese: "運動鞋", english: "trainers", jyutping: "wan6 dung6 haai4", topic: "Family" },
  { id: 560, chinese: "裙子", english: "skirt", jyutping: "kwan4 zi2", topic: "Family" },
  { id: 561, chinese: "褲子", english: "trousers", jyutping: "fu3 zi2", topic: "Family" },
  { id: 562, chinese: "毛衣", english: "sweater", jyutping: "mou4 ji1", topic: "Family" },
  { id: 563, chinese: "手錶", english: "watch", jyutping: "sau2 biu1", topic: "Family" },
  { id: 564, chinese: "童年", english: "childhood", jyutping: "tung4 nin4", topic: "Childhood" },
  { id: 565, chinese: "小時候", english: "childhood", jyutping: "siu2 si4 hau6", topic: "Childhood" },
  { id: 566, chinese: "兒童", english: "child", jyutping: "ji4 tung4", topic: "Childhood" },
  { id: 567, chinese: "孩子", english: "kid", jyutping: "haai4 zi2", topic: "Childhood" },
  { id: 568, chinese: "長大", english: "to grow up", jyutping: "zoeng2 daai6", topic: "Childhood" },
  { id: 569, chinese: "成人", english: "adult", jyutping: "sing4 jan4", topic: "Childhood" },
  { id: 570, chinese: "講故事", english: "to tell a story", jyutping: "gong2 gu3 si6", topic: "Childhood" },
  { id: 571, chinese: "更喜歡", english: "to prefer", jyutping: "gang3 hei2 fun1", topic: "Childhood" },
  { id: 572, chinese: "玩具", english: "toy", jyutping: "wun6 geoi6", topic: "Childhood" },

  // Topic Area D: Environment & Modern World
  { id: 573, chinese: "山", english: "mountain", jyutping: "saan1", topic: "Environment Issues" },
  { id: 574, chinese: "河", english: "river", jyutping: "ho4", topic: "Environment Issues" },
  { id: 575, chinese: "江", english: "river (large)", jyutping: "gong1", topic: "Environment Issues" },
  { id: 576, chinese: "湖", english: "lake", jyutping: "wu4", topic: "Environment Issues" },
  { id: 577, chinese: "海", english: "sea", jyutping: "hoi2", topic: "Environment Issues" },
  { id: 578, chinese: "土地", english: "land", jyutping: "tou2 dei6", topic: "Environment Issues" },
  { id: 579, chinese: "花", english: "flower", jyutping: "faa1", topic: "Environment Issues", synonym_group: 40 },
  { id: 580, chinese: "草", english: "grass", jyutping: "cou2", topic: "Environment Issues" },
  { id: 581, chinese: "樹", english: "tree", jyutping: "syu6", topic: "Environment Issues" },
  { id: 582, chinese: "森林", english: "forest", jyutping: "sam1 lam4", topic: "Environment Issues" },
  { id: 583, chinese: "天空", english: "sky", jyutping: "tin1 hung1", topic: "Environment Issues" },
  { id: 584, chinese: "新鮮", english: "fresh", jyutping: "san1 sin1", topic: "Environment Issues" },
  { id: 585, chinese: "太陽", english: "sun", jyutping: "taai3 joeng4", topic: "Environment Issues" },
  { id: 586, chinese: "月亮", english: "moon", jyutping: "jyut6 loeng6", topic: "Environment Issues" },
  { id: 587, chinese: "紙", english: "paper", jyutping: "zi2", topic: "Environment Issues" },
  { id: 588, chinese: "春天", english: "spring", jyutping: "ceon1 tin1", topic: "Weather" },
  { id: 589, chinese: "夏天", english: "summer", jyutping: "haa6 tin1", topic: "Weather" },
  { id: 590, chinese: "秋天", english: "autumn", jyutping: "cau1 tin1", topic: "Weather" },
  { id: 591, chinese: "冬天", english: "winter", jyutping: "dung1 tin1", topic: "Weather" },
  { id: 592, chinese: "晴天", english: "sunny", jyutping: "cing4 tin1", topic: "Weather" },
  { id: 593, chinese: "多雲", english: "cloudy", jyutping: "do1 wan4", topic: "Weather" },
  { id: 594, chinese: "風", english: "wind", jyutping: "fung1", topic: "Weather" },
  { id: 595, chinese: "颳風", english: "windy", jyutping: "gwaat3 fung1", topic: "Weather" },
  { id: 596, chinese: "雨", english: "rain", jyutping: "jyu5", topic: "Weather" },
  { id: 597, chinese: "下雨", english: "to rain", jyutping: "haa6 jyu5", topic: "Weather" },
  { id: 598, chinese: "雪", english: "snow", jyutping: "syut3", topic: "Weather" },
  { id: 599, chinese: "霧", english: "fog", jyutping: "mou6", topic: "Weather" },
  { id: 600, chinese: "東", english: "east", jyutping: "dung1", topic: "Transport" },
  { id: 601, chinese: "南", english: "south", jyutping: "naam4", topic: "Transport" },
  { id: 602, chinese: "西", english: "west", jyutping: "sai1", topic: "Transport" },
  { id: 603, chinese: "北", english: "north", jyutping: "bak1", topic: "Transport" },
  { id: 604, chinese: "歡迎", english: "welcome", jyutping: "fun1 jing4", topic: "Transport" },
  { id: 605, chinese: "火車", english: "train", jyutping: "fo2 ce1", topic: "Transport" },
  { id: 606, chinese: "汽車", english: "car", jyutping: "hei3 ce1", topic: "Transport" },
  { id: 607, chinese: "公共汽車", english: "bus", jyutping: "gung1 gung6 hei3 ce1", topic: "Transport" },
  { id: 608, chinese: "計程車", english: "taxi", jyutping: "gai3 cing4 ce1", topic: "Transport", synonym_group: 30 },
  { id: 609, chinese: "的士", english: "taxi", jyutping: "dik1 si2", topic: "Transport", synonym_group: 30 },
  { id: 610, chinese: "校車", english: "school bus", jyutping: "haau6 ce1", topic: "Transport" },
  { id: 611, chinese: "馬", english: "horse", jyutping: "maa5", topic: "Transport" },
  { id: 612, chinese: "站", english: "station, stop", jyutping: "zaam6", topic: "Transport" },
  { id: 613, chinese: "地鐵", english: "underground, subway", jyutping: "dei6 tit3", topic: "Transport" },
  { id: 614, chinese: "飛機", english: "plane", jyutping: "fei1 gei1", topic: "Transport" },
  { id: 615, chinese: "飛機場", english: "airport", jyutping: "fei1 gei1 coeng4", topic: "Transport" },
  { id: 616, chinese: "船", english: "boat", jyutping: "syun4", topic: "Transport" },
  { id: 617, chinese: "自行車", english: "bicycle", jyutping: "zi6 hang4 ce1", topic: "Transport", synonym_group: 31 },
  { id: 618, chinese: "單車", english: "bicycle", jyutping: "daan1 ce1", topic: "Transport", synonym_group: 31 },
  { id: 619, chinese: "走路", english: "to walk", jyutping: "zau2 lou6", topic: "Transport" },
  { id: 620, chinese: "行人", english: "pedestrian", jyutping: "haang4 jan4", topic: "Transport" },
  { id: 621, chinese: "人行道", english: "pavement", jyutping: "jan4 hong4 dou6", topic: "Transport" },
  { id: 622, chinese: "票", english: "ticket", jyutping: "piu3", topic: "Transport" },
  { id: 623, chinese: "免費", english: "free", jyutping: "min5 fai3", topic: "Transport" },
  { id: 624, chinese: "新聞", english: "news", jyutping: "san1 man4", topic: "Media" },
  { id: 625, chinese: "節目", english: "program", jyutping: "zit3 muk6", topic: "Media" },
  { id: 626, chinese: "名人", english: "celebrities", jyutping: "ming4 jan4", topic: "Media" },
  { id: 627, chinese: "電臺", english: "radio station", jyutping: "din6 toi4", topic: "Media" },
  { id: 628, chinese: "電影", english: "film", jyutping: "din6 jing2", topic: "Media" },
  { id: 629, chinese: "電視劇", english: "soap opera", jyutping: "din6 si6 kek6", topic: "Media" },
  { id: 630, chinese: "音樂會", english: "concert", jyutping: "jam1 ngok6 wui2", topic: "Media" },
  { id: 631, chinese: "表演", english: "performance", jyutping: "biu2 jin2", topic: "Media" },
  { id: 632, chinese: "舞", english: "dance", jyutping: "mou5", topic: "Media" },
  { id: 633, chinese: "國際", english: "international", jyutping: "gwok3 zai3", topic: "Media" },
  { id: 634, chinese: "國內", english: "domestic", jyutping: "gwok3 noi6", topic: "Media" },
  { id: 635, chinese: "世界", english: "world", jyutping: "sai3 gaai3", topic: "Media" },
  { id: 636, chinese: "本地", english: "local", jyutping: "bun2 dei6", topic: "Media" },
  { id: 637, chinese: "有錢人", english: "wealthy people", jyutping: "jau5 cin2 jan4", topic: "Media" },
  { id: 638, chinese: "電話", english: "telephone", jyutping: "din6 waa2", topic: "Technology" },
  { id: 639, chinese: "手機", english: "mobile", jyutping: "sau2 gei1", topic: "Technology" },
  { id: 640, chinese: "電腦", english: "computer", jyutping: "din6 nou5", topic: "Technology" },
  { id: 641, chinese: "電腦遊戲", english: "computer game", jyutping: "din6 nou5 jau4 hei3", topic: "Technology" },
  { id: 642, chinese: "電子郵件", english: "email", jyutping: "din6 zi2 jau4 gin2", topic: "Technology" },
  { id: 643, chinese: "上網", english: "surf the web", jyutping: "soeng5 mong5", topic: "Technology" },
  { id: 644, chinese: "網友", english: "e-pal", jyutping: "mong5 jau5", topic: "Technology" },
  { id: 645, chinese: "網站", english: "website", jyutping: "mong5 zaam6", topic: "Technology" },
  { id: 646, chinese: "網頁", english: "webpage", jyutping: "mong5 jip6", topic: "Technology" },
  { id: 647, chinese: "網址", english: "email/web address", jyutping: "mong5 zi2", topic: "Technology" },
  { id: 648, chinese: "下載", english: "download", jyutping: "haa6 zoi3", topic: "Technology" },
  { id: 649, chinese: "詞典", english: "dictionary", jyutping: "ci4 din2", topic: "Technology", synonym_group: 41 },
  { id: 650, chinese: "電子產品", english: "electronic gadgets", jyutping: "din6 zi2 caan2 ban2", topic: "Technology" },
  { id: 651, chinese: "短信", english: "text message", jyutping: "dyun2 seon3", topic: "Technology" },
  { id: 652, chinese: "平板電腦", english: "tablet/iPad", jyutping: "ping4 baan2 din6 nou5", topic: "Technology" },

  // Topic Area E: Social & Food
  { id: 653, chinese: "祝", english: "to wish", jyutping: "zuk1", topic: "Special Occasions" },
  { id: 654, chinese: "新年好", english: "Happy New Year", jyutping: "san1 nin4 hou2", topic: "Special Occasions" },
  { id: 655, chinese: "餐廳", english: "restaurant", jyutping: "caan1 teng1", topic: "Food & Drink", synonym_group: 37 },
  { id: 656, chinese: "飯館", english: "restaurant", jyutping: "faan6 gun2", topic: "Food & Drink", synonym_group: 37 },
  { id: 657, chinese: "外賣", english: "takeaway", jyutping: "ngoi6 maai6", topic: "Food & Drink" },
  { id: 658, chinese: "菜單", english: "menu", jyutping: "coi3 daan1", topic: "Food & Drink" },
  { id: 659, chinese: "點菜", english: "to order", jyutping: "dim2 coi3", topic: "Food & Drink" },
  { id: 660, chinese: "空閒時間", english: "free time", jyutping: "hung1 haan4 si4 gaan1", topic: "Hobbies" },
  { id: 661, chinese: "愛好", english: "hobby", jyutping: "oi3 hou3", topic: "Hobbies" },
  { id: 662, chinese: "興趣", english: "interest", jyutping: "hing3 ceoi3", topic: "Hobbies" },
  { id: 663, chinese: "小說", english: "novel", jyutping: "siu2 syut3", topic: "Hobbies" },
  { id: 664, chinese: "散步", english: "take a walk", jyutping: "saan3 bou6", topic: "Hobbies" },
  { id: 665, chinese: "爬山", english: "climbing hills", jyutping: "paa4 saan1", topic: "Hobbies" },
  { id: 666, chinese: "運動", english: "sport", jyutping: "wan6 dung6", topic: "Hobbies" },
  { id: 667, chinese: "足球", english: "football", jyutping: "zuk1 kau4", topic: "Hobbies" },
  { id: 668, chinese: "網球", english: "tennis", jyutping: "mong5 kau4", topic: "Hobbies" },
  { id: 669, chinese: "乒乓球", english: "table tennis", jyutping: "bing1 bam1 kau4", topic: "Hobbies" },
  { id: 670, chinese: "籃球", english: "basketball", jyutping: "laam4 kau4", topic: "Hobbies" },
  { id: 671, chinese: "羽毛球", english: "badminton", jyutping: "jyu5 mou4 kau4", topic: "Hobbies" },
  { id: 672, chinese: "游泳", english: "swimming", jyutping: "jau4 wing6", topic: "Hobbies" },
  { id: 673, chinese: "跑步", english: "running", jyutping: "paau2 bou6", topic: "Hobbies" },
  { id: 674, chinese: "滑雪", english: "skiing", jyutping: "waat6 syut3", topic: "Hobbies" },
  { id: 675, chinese: "看書", english: "reading", jyutping: "hon3 syu1", topic: "Hobbies" },
  { id: 676, chinese: "隊", english: "team", jyutping: "deoi2", topic: "Hobbies" },
  { id: 677, chinese: "隊員", english: "team member", jyutping: "deoi2 jyun4", topic: "Hobbies" },
  { id: 678, chinese: "運動員", english: "athlete", jyutping: "wan6 dung6 jyun4", topic: "Hobbies" },
  { id: 679, chinese: "比賽", english: "match, competition", jyutping: "bei2 coi3", topic: "Hobbies" },
  { id: 680, chinese: "看報", english: "read newspaper", jyutping: "hon3 bou3", topic: "Hobbies" },
  { id: 681, chinese: "買東西", english: "shopping", jyutping: "maai5 dung1 sai1", topic: "Shopping" },
  { id: 682, chinese: "便宜", english: "cheap", jyutping: "peng4 ji4", topic: "Shopping" },
  { id: 683, chinese: "貴", english: "expensive", jyutping: "gwai3", topic: "Shopping" },
  { id: 684, chinese: "錢", english: "money", jyutping: "cin4", topic: "Shopping" },
  { id: 685, chinese: "錢包", english: "wallet", jyutping: "cin4 baau1", topic: "Shopping" },
  { id: 686, chinese: "付錢", english: "to pay", jyutping: "fu6 cin2", topic: "Shopping" },
  { id: 687, chinese: "信用卡", english: "credit card", jyutping: "seon3 jung6 kaat1", topic: "Shopping" },
  { id: 688, chinese: "零花錢", english: "pocket money", jyutping: "ling4 faa1 cin2", topic: "Shopping", synonym_group: 35 },
  { id: 689, chinese: "減價", english: "sale, discount", jyutping: "gaam2 gaa3", topic: "Shopping" },
  { id: 690, chinese: "多少錢", english: "how much", jyutping: "do1 siu2 cin2", topic: "Shopping" },
  { id: 691, chinese: "商店", english: "shop", jyutping: "soeng1 dim3", topic: "Shopping" },
  { id: 692, chinese: "關門", english: "close", jyutping: "gwaan1 mun4", topic: "Shopping" },
  { id: 693, chinese: "購物中心", english: "shopping centre", jyutping: "gau3 mat6 zung1 sam1", topic: "Shopping" },
  { id: 694, chinese: "超級市場", english: "supermarket", jyutping: "ciu1 kap1 si5 coeng4", topic: "Shopping" },
  { id: 695, chinese: "百貨公司", english: "department store", jyutping: "baak3 fo3 gung1 si1", topic: "Shopping" },
  { id: 696, chinese: "鎊", english: "pound sterling", jyutping: "bong6", topic: "Shopping" },
  { id: 697, chinese: "元", english: "yuan", jyutping: "jyun4", topic: "Shopping", synonym_group: 39 },
  { id: 698, chinese: "塊", english: "kuai (yuan)", jyutping: "faai3", topic: "Shopping", synonym_group: 39 },
  { id: 699, chinese: "歐元", english: "euro", jyutping: "au1 jyun4", topic: "Shopping" },
  { id: 700, chinese: "號 (大小)", english: "size", jyutping: "hou6", topic: "Shopping" },
  { id: 701, chinese: "身體", english: "body", jyutping: "san1 tai2", topic: "Health" },
  { id: 702, chinese: "病", english: "ill", jyutping: "beng6", topic: "Health" },
  { id: 703, chinese: "酒", english: "wine, alcohol", jyutping: "zau2", topic: "Health" },
  { id: 704, chinese: "吸煙", english: "smoking", jyutping: "kap1 jin1", topic: "Health" },
  { id: 705, chinese: "疼", english: "ache, pain", jyutping: "tang4", topic: "Health", synonym_group: 42 },
  { id: 706, chinese: "痛", english: "ache, pain", jyutping: "tung3", topic: "Health", synonym_group: 42 },
  { id: 707, chinese: "發燒", english: "have a fever", jyutping: "faat3 siu1", topic: "Health" },
  { id: 708, chinese: "感冒", english: "have a cold", jyutping: "gam2 mou6", topic: "Health" },
  { id: 709, chinese: "咳嗽", english: "cough", jyutping: "kat1 sau3", topic: "Health" },
  { id: 710, chinese: "頭", english: "head", jyutping: "tau4", topic: "Health" },
  { id: 711, chinese: "牙", english: "tooth", jyutping: "nga4", topic: "Health" },
  { id: 712, chinese: "耳", english: "ear", jyutping: "ji5", topic: "Health" },
  { id: 713, chinese: "心", english: "heart", jyutping: "sam1", topic: "Health" },
  { id: 714, chinese: "肚子", english: "stomach", jyutping: "tou5 zi2", topic: "Health" },
  { id: 715, chinese: "手", english: "hand", jyutping: "sau2", topic: "Health" },
  { id: 716, chinese: "腳", english: "foot", jyutping: "goek3", topic: "Health" },
  { id: 717, chinese: "米飯", english: "rice", jyutping: "mai5 faan6", topic: "Food & Drink" },
  { id: 718, chinese: "早飯", english: "breakfast", jyutping: "zou2 faan6", topic: "Food & Drink", synonym_group: 32 },
  { id: 719, chinese: "早餐", english: "breakfast", jyutping: "zou2 caan1", topic: "Food & Drink", synonym_group: 32 },
  { id: 720, chinese: "午飯", english: "lunch", jyutping: "ng5 faan6", topic: "Food & Drink", synonym_group: 33 },
  { id: 721, chinese: "午餐", english: "lunch", jyutping: "ng5 caan1", topic: "Food & Drink", synonym_group: 33 },
  { id: 722, chinese: "晚飯", english: "dinner", jyutping: "maan5 faan6", topic: "Food & Drink", synonym_group: 34 },
  { id: 723, chinese: "晚餐", english: "dinner", jyutping: "maan5 caan1", topic: "Food & Drink", synonym_group: 34 },
  { id: 724, chinese: "麵包", english: "bread", jyutping: "min6 baau1", topic: "Food & Drink" },
  { id: 725, chinese: "麵條", english: "noodles", jyutping: "min6 tiu4", topic: "Food & Drink" },
  { id: 726, chinese: "魚", english: "fish", jyutping: "jyu2", topic: "Food & Drink" },
  { id: 727, chinese: "雞", english: "chicken", jyutping: "gai1", topic: "Food & Drink" },
  { id: 728, chinese: "鴨", english: "duck", jyutping: "aap3", topic: "Food & Drink" },
  { id: 729, chinese: "蛋", english: "egg", jyutping: "daan2", topic: "Food & Drink" },
  { id: 730, chinese: "炒", english: "fried", jyutping: "caau2", topic: "Food & Drink" },
  { id: 731, chinese: "烤", english: "roast", jyutping: "haau1", topic: "Food & Drink" },
  { id: 732, chinese: "肉", english: "meat", jyutping: "juk6", topic: "Food & Drink" },
  { id: 733, chinese: "豬肉", english: "pork", jyutping: "zyu1 juk6", topic: "Food & Drink" },
  { id: 734, chinese: "牛肉", english: "beef", jyutping: "ngau4 juk6", topic: "Food & Drink" },
  { id: 735, chinese: "點心", english: "snack", jyutping: "dim2 sam1", topic: "Food & Drink" },
  { id: 736, chinese: "青菜", english: "vegetable", jyutping: "ceng1 coi3", topic: "Food & Drink" },
  { id: 737, chinese: "水", english: "water", jyutping: "seoi2", topic: "Food & Drink" },
  { id: 738, chinese: "開水", english: "boiled water", jyutping: "hoi1 seoi2", topic: "Food & Drink" },
  { id: 739, chinese: "水果", english: "fruit", jyutping: "seoi2 gwo2", topic: "Food & Drink" },
  { id: 740, chinese: "果汁", english: "fruit juice", jyutping: "gwo2 zap1", topic: "Food & Drink" },
  { id: 741, chinese: "牛奶", english: "milk", jyutping: "ngau4 naai5", topic: "Food & Drink" },
  { id: 742, chinese: "湯", english: "soup", jyutping: "tong1", topic: "Food & Drink" },
  { id: 743, chinese: "汽水", english: "fizzy drinks", jyutping: "hei3 seoi2", topic: "Food & Drink" },
  { id: 744, chinese: "茶", english: "tea", jyutping: "caa4", topic: "Food & Drink" },
  { id: 745, chinese: "咖啡", english: "coffee", jyutping: "gaa3 fe1", topic: "Food & Drink" },
  { id: 746, chinese: "餃子", english: "dumpling", jyutping: "gaau2 zi2", topic: "Food & Drink" },
  { id: 747, chinese: "粽子", english: "rice dumpling", jyutping: "zung2 zi2", topic: "Food & Drink" },
  { id: 748, chinese: "月餅", english: "moon cake", jyutping: "jyut6 beng2", topic: "Food & Drink" }
];